// Generated by CoffeeScript 1.10.0
(function() {
  var Handler, colors, striptags;

  striptags = require('striptags');

  colors = require('colors');

  Handler = (function() {
    function Handler() {
      this.conversations = {};
      this.contacts = {};
    }

    Handler.prototype.attach = function(emitter) {
      emitter.on('message', (function(_this) {
        return function(event) {
          var contact, message, topic;
          topic = _this.conversations[event.conversation_id].bgBlue.white;
          contact = _this.contacts[event.profile_id].white.bgBlack;
          message = striptags(event.message);
          return console.log(topic + "  " + contact + " " + message);
        };
      })(this));
      emitter.on('conv', (function(_this) {
        return function(event) {
          if (!event.topic) {
            return;
          }
          return _this.conversations[event.conversation_id] = event.topic;
        };
      })(this));
      return emitter.on('contact', (function(_this) {
        return function(event) {
          return _this.contacts[event.account_id] = event.display_name;
        };
      })(this));
    };

    return Handler;

  })();

  module.exports = Handler;

}).call(this);
