// Generated by CoffeeScript 1.10.0
(function() {
  var Fleep, Handler, emitter, events, fleep, handler;

  Fleep = require('./fleep');

  events = require('events');

  Handler = require('./handler');

  if (!process.env.FLEEP_EMAIL || !process.env.FLEEP_PASSWORD) {
    console.error('FLEEP_EMAIL and FLEEP_PASSWORD environment variables are required.');
    process.exit();
  }

  emitter = new events.EventEmitter;

  fleep = new Fleep(emitter);

  handler = new Handler;

  handler.attach(emitter);

  fleep.login(process.env.FLEEP_EMAIL, process.env.FLEEP_PASSWORD);

  emitter.on('login.complete', function(client) {
    console.info('Listening for Fleep events...');
    return fleep.poll();
  });

}).call(this);
